/*
 * aSlicer - 3D model processing tool.
 * Copyright (C) 2026 cz.ad.print3d.aslicer contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package cz.ad.print3d.aslicer.logic.core;

import clipper2.Clipper;
import clipper2.core.ClipType;
import clipper2.core.FillRule;
import clipper2.core.Path64;
import clipper2.core.Paths64;
import clipper2.core.Point64;
import clipper2.core.Rect64;
import clipper2.engine.Clipper64;
import clipper2.offset.EndType;
import clipper2.offset.JoinType;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * EdgeGenerator generates monotonic lines infill for 3D printing.
 * The monotonic lines algorithm ensures that the lines are printed in a single, consistent direction,
 * which improves surface quality by reducing the "scarring" effect where paths meet.
 * <br/>
 * This implementation takes slices generated by {@link Slicer} as input.
 */
public class ShellGenerator {

    private static final double SCALE = 1000.0;
    
    /** Overlap with the external core (percentage 0.0 to 1.0). */
    private float overlap = 0.15f;
    
    /**
     * Sets the overlap with the external core.
     * 
     * @param overlap Percentage of overlap (e.g., 0.15 for 15%).
     */
    public void setOverlap(float overlap) {
        this.overlap = overlap;
    }

    /**
     * Generates monotonic infill lines for a set of layers.
     * 
     * @param layers     The list of layers (slices) from Slicer.
     * @param nozzleSize The nozzle diameter (mm).
     * @param spacing    The distance between parallel lines (mm).
     * @param angleDeg   The pattern angle (degrees).
     * @return A list of Paths64 containing the generated lines for each layer.
     */
    public List<Paths64> generateMonotonicInfill(List<Paths64> layers, float nozzleSize, float spacing, float angleDeg) {
        List<Paths64> result = new ArrayList<>();
        for (Paths64 layer : layers) {
            result.add(generateLayerInfill(layer, nozzleSize, spacing, angleDeg));
        }
        return result;
    }

    /**
     * Generates monotonic infill lines for a single layer.
     * 
     * @param layer      The layer boundary paths.
     * @param nozzleSize The nozzle diameter (mm).
     * @param spacing    The distance between parallel lines (mm).
     * @param angleDeg   The pattern angle (degrees).
     * @return The generated infill paths.
     */
    public Paths64 generateLayerInfill(Paths64 layer, float nozzleSize, float spacing, float angleDeg) {
        if (layer == null || layer.isEmpty()) {
            return new Paths64();
        }

        // Apply overlap: inflate boundary slightly outwards
        // Slic3r/PrusaSlicer uses overlap to ensure infill bonds with the shell.
        double offset = nozzleSize * overlap * SCALE;
        Paths64 infillBoundary = Clipper.InflatePaths(layer, offset, JoinType.Miter, EndType.Polygon);
        
        // Calculate bounding box of the boundary
        Rect64 bounds = Clipper.GetBounds(infillBoundary);
        long centerX = (bounds.left + bounds.right) / 2;
        long centerY = (bounds.top + bounds.bottom) / 2;
        
        // Calculate the range needed to cover the rotated boundary
        long dx = bounds.right - bounds.left;
        long dy = bounds.bottom - bounds.top;
        long range = (long) Math.sqrt(dx * dx + dy * dy) + (long)(spacing * SCALE);

        // Generate parallel lines covering the whole range
        Paths64 lines = generateParallelLines(centerX, centerY, range, spacing, angleDeg);
        
        // Clip lines to the boundary
        Clipper64 clipper = new Clipper64();
        clipper.AddOpenSubject(lines);
        clipper.AddClip(infillBoundary);
        Paths64 clippedLines = new Paths64();
        clipper.Execute(ClipType.Intersection, FillRule.EvenOdd, new Paths64(), clippedLines);
        
        // Sort lines for monotonic printing
        return sortMonotonically(clippedLines, angleDeg);
    }

    /**
     * Generates parallel lines covering a square area.
     */
    private Paths64 generateParallelLines(long cX, long cY, long range, float spacing, float angleDeg) {
        Paths64 lines = new Paths64();
        double angleRad = Math.toRadians(angleDeg);
        double cosA = Math.cos(angleRad);
        double sinA = Math.sin(angleRad);
        
        double perpAngleRad = angleRad + Math.PI / 2.0;
        double perpCosA = Math.cos(perpAngleRad);
        double perpSinA = Math.sin(perpAngleRad);
        
        long step = Math.round(spacing * SCALE);
        long halfRange = range / 2;
        
        for (long d = -halfRange; d <= halfRange; d += step) {
            long startX = Math.round(cX + d * perpCosA - halfRange * cosA);
            long startY = Math.round(cY + d * perpSinA - halfRange * sinA);
            long endX = Math.round(cX + d * perpCosA + halfRange * cosA);
            long endY = Math.round(cY + d * perpSinA + halfRange * sinA);
            
            Path64 line = new Path64();
            line.add(new Point64(startX, startY));
            line.add(new Point64(endX, endY));
            lines.add(line);
        }
        
        return lines;
    }

    /**
     * Sorts the paths to ensure monotonic printing order.
     * This sorts paths by their projection onto the perpendicular to the pattern angle.
     */
    private Paths64 sortMonotonically(Paths64 paths, float angleDeg) {
        if (paths.isEmpty()) return paths;
        
        double perpAngleRad = Math.toRadians(angleDeg + 90.0);
        double cosA = Math.cos(perpAngleRad);
        double sinA = Math.sin(perpAngleRad);
        
        List<Path64> sorted = new ArrayList<>(paths);
        sorted.sort(Comparator.comparingDouble(path -> {
            Point64 p = path.getFirst();
            return p.x * cosA + p.y * sinA;
        }));
        
        // Ensure consistent direction for each line segment
        // PrusaSlicer's monotonic lines ensure they all go in the same direction 
        // if possible, but for open paths after clipping, we just ensure they are
        // ordered monotonically across the surface.
        
        Paths64 result = new Paths64();
        result.addAll(sorted);
        return result;
    }
}
