/*
 * aSlicer - 3D model processing tool.
 * Copyright (C) 2026 cz.ad.print3d.aslicer contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package cz.ad.print3d.aslicer.logic.core;

import clipper2.core.Paths64;
import clipper2.offset.ClipperOffset;
import clipper2.offset.EndType;
import clipper2.offset.JoinType;

import java.util.ArrayList;
import java.util.List;

/**
 * WallTracer generates toolpaths for walls (perimeters) of a 3D model.
 * It uses the layer polygons generated by the Slicer and offsets them inwards
 * based on the nozzle size.
 *
 * The implementation is inspired by PrusaSlicer and BambuStudio, which use
 * Clipper's offsetting functionality to generate perimeters. These slicers
 * typically generate concentric paths by iteratively offsetting the original
 * boundary inwards.
 *
 * Note: Coordinates are scaled by 1000.0 to match the scaling used in the Slicer
 * class and to avoid precision issues with Clipper2's integer-based arithmetic.
 */
public class WallTracer {
    /**
     * Scaling factor to convert between float units and Clipper2's long units.
     */
    private static final double SCALE = 1000.0;

    /**
     * Generates wall paths for all layers in a model.
     *
     * @param layers      List of layer polygons as returned by the {@link Slicer}.
     * @param nozzleSize  The width of the extrusion line (typically equal to nozzle diameter).
     * @param wallCount   The number of perimeter walls to generate.
     * @return A list of layers, where each layer contains a list of {@link Paths64} objects.
     *         Each {@link Paths64} represents one wall level (contour), starting from the outermost.
     */
    public List<List<Paths64>> traceWalls(List<Paths64> layers, float nozzleSize, int wallCount) {
        if (layers == null) {
            return new ArrayList<>();
        }
        List<List<Paths64>> allLayersWalls = new ArrayList<>();

        for (Paths64 layerPaths : layers) {
            allLayersWalls.add(traceWallsForLayer(layerPaths, nozzleSize, wallCount));
        }

        return allLayersWalls;
    }

    /**
     * Generates concentric wall paths for a single layer.
     *
     * @param layerPaths  The polygons defining the boundary of the current layer.
     * @param nozzleSize  The width of the extrusion line.
     * @param wallCount   The number of perimeter walls to generate.
     * @return A list of {@link Paths64}, where each element is a set of paths for a single wall level.
     *         If the geometry is too thin to accommodate all requested walls, fewer walls will be returned.
     */
    public List<Paths64> traceWallsForLayer(Paths64 layerPaths, float nozzleSize, int wallCount) {
        if (layerPaths == null || layerPaths.isEmpty() || wallCount <= 0 || nozzleSize <= 0) {
            return new ArrayList<>();
        }

        List<Paths64> layerWalls = new ArrayList<>();
        
        // We use Miter join type with a miter limit of 2.0 to keep corners sharp but avoid excessive spikes.
        // This is a common approach in 3D printing slicing.
        JoinType joinType = JoinType.Miter;
        EndType endType = EndType.Polygon;

        ClipperOffset offset = new ClipperOffset();
        offset.AddPaths(layerPaths, joinType, endType);

        for (int i = 0; i < wallCount; i++) {
            // The first wall center should be at half-extrusion-width from the boundary.
            // Subsequent wall centers are at (half + (i * full)) extrusion width from the boundary.
            double delta = -(nozzleSize / 2.0 + i * (double)nozzleSize) * SCALE;
            
            Paths64 wallPaths = new Paths64();
            offset.Execute(delta, wallPaths);
            
            if (!wallPaths.isEmpty()) {
                layerWalls.add(wallPaths);
            } else {
                // Geometry too thin for further inward perimeters
                break;
            }
        }
        
        return layerWalls;
    }
}
