/*
 * aSlicer - 3D model processing tool.
 * Copyright (C) 2026 cz.ad.print3d.aslicer contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package cz.ad.print3d.aslicer.logic.model.parser.gcode;

import cz.ad.print3d.aslicer.logic.model.format.gcode.core.*;
import cz.ad.print3d.aslicer.logic.model.format.gcode.flavor.*;
import cz.ad.print3d.aslicer.logic.model.parser.ModelParser;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.charset.StandardCharsets;

/**
 * Parser for G-code files that implements {@link ModelParser}.
 * This parser reads from a {@link ReadableByteChannel} and converts the binary data
 * into a structured {@link GCode} object.
 *
 * <p>It uses {@link GCodeParser} to parse individual lines according to ISO 6983.</p>
 */
public class GCodeModelParser implements ModelParser<GCode> {

    /**
     * Parses G-code from the given channel.
     * Currently, it defaults to {@link MarlinGCode} flavor.
     *
     * @param channel the input binary channel containing G-code text
     * @return the parsed G-code DTO
     * @throws IOException if an I/O error occurs during parsing
     */
    @Override
    public GCode parse(ReadableByteChannel channel) throws IOException {
        GCode gcode = new MarlinGCode();
        try (BufferedReader reader = new BufferedReader(Channels.newReader(channel, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                GCodeBlock block = GCodeParser.parseLine(line);
                if (block != null) {
                    gcode.addCommand(block);
                    
                    // Simple metadata extraction from comments
                    extractMetadata(gcode, block);
                }
            }
        }
        return gcode;
    }

    /**
     * Extracts metadata from G-code comments.
     * Many slicers put information like "generated by Slic3r" or "layer_height = 0.2" in comments.
     *
     * @param gcode the G-code object to populate
     * @param block the block to check for metadata
     */
    private void extractMetadata(GCode gcode, GCodeBlock block) {
        block.getComment().ifPresent(comment -> {
            if (comment.contains("=")) {
                String[] parts = comment.split("=", 2);
                if (parts.length == 2) {
                    gcode.addMetadata(parts[0].trim(), parts[1].trim());
                }
            } else if (comment.startsWith("generated by")) {
                gcode.addMetadata("slicer", comment.substring("generated by".length()).trim());
            }
        });
    }
}
