; generated by aSlicer - free G-code example
; flavor = Marlin
; layer_height = 0.2
; initial_layer_height = 0.3
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G28 ; home all axes
N1 G1 Z5 F5000 ; lift nozzle
N2 G1 X10 Y10 F3000 ; move to start position
N3 G1 Z0.3 ; move to first layer height
N4 G1 X50 Y10 E2.0 F1000 ; extrude a line
N5 G1 X50 Y50 E4.0 ; extrude another line
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
G28 X0 ; home X axis
M84 ; disable motors
; end of file
