/*
 * aSlicer - 3D model processing tool.
 * Copyright (C) 2026 cz.ad.print3d.aslicer contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package cz.ad.print3d.aslicer.logic.core.filler;

import clipper2.Clipper;
import clipper2.core.ClipType;
import clipper2.core.FillRule;
import clipper2.core.Path64;
import clipper2.core.Paths64;
import clipper2.core.Point64;
import clipper2.core.Rect64;
import clipper2.engine.Clipper64;
import clipper2.offset.EndType;
import clipper2.offset.JoinType;
import cz.ad.print3d.aslicer.logic.core.WallTracer;

import java.util.List;

/**
 * BasicFillerGenerator implements various infill patterns for 3D printing.
 * It uses Clipper2-java to perform boolean intersection operations between
 * the infill pattern (lines) and the layer boundary.
 *
 * Supported patterns:
 * - RECTILINEAR: Parallel lines in a single direction.
 * - GRID: Two sets of parallel lines, usually perpendicular.
 * - TRIANGLES: Three sets of parallel lines at 60-degree intervals.
 *
 * The implementation is inspired by Slic3r/PrusaSlicer, generating lines
 * that cover the bounding box of the part and clipping them to the boundary.
 */
public class BasicFillerGenerator implements FillerGenerator {

    private InfillPattern pattern = InfillPattern.RECTILINEAR;

    /**
     * Sets the infill pattern to use.
     * @param pattern The pattern to use.
     */
    public void setPattern(InfillPattern pattern) {
        this.pattern = pattern;
    }

    /**
     * Scaling factor to convert between float units and Clipper2's long units.
     */
    private static final double SCALE = 1000.0;

    /**
     * Supported infill patterns.
     */
    public enum InfillPattern {
        /** Parallel lines in one direction per layer. */
        RECTILINEAR,
        /** Two sets of parallel lines in each layer (0° and 90° relative to base angle). */
        GRID,
        /** Three sets of parallel lines in each layer (0°, 60°, and 120° relative to base angle). */
        TRIANGLES
    }

    /**
     * Generates infill paths for a given boundary.
     *
     * The boundary for infill is determined as follows:
     * 1. If walls are provided, the infill is bounded by the innermost wall,
     *    offset inwards by half the nozzle size to reach the actual edge of the extrusion.
     * 2. If no walls are provided, the original layer boundary is used.
     *
     * The algorithm generates long parallel lines covering the bounding box
     * of the infill area and clips them using Clipper64's open path intersection.
     *
     * @param walls        The list of wall paths for the current layer, as generated by {@link WallTracer}.
     *                     Each element in the list represents a wall level (from outer to inner).
     * @param originalLayer The original boundary paths of the layer (used if no walls are present).
     * @param nozzleSize   The width of the extrusion line (nozzle diameter).
     *                     Used to calculate the infill boundary offset.
     * @param spacing      The distance between parallel infill lines (in model units, e.g., mm).
     * @param angle        The base angle for the infill lines in degrees.
     * @param altitude     The vertical coordinate (Y) of the current layer.
     * @return A {@link Paths64} containing the clipped infill lines as open paths.
     */
    @Override
    public Paths64 generateInfill(List<Paths64> walls, Paths64 originalLayer, float nozzleSize, float spacing, float angle, float altitude) {
        Paths64 infillBoundary;
        if (walls == null || walls.isEmpty()) {
            // If no walls, we use the original layer boundary. 
            // In a real slicer, we might still offset it by nozzleSize/2.
            infillBoundary = originalLayer;
        } else {
            // Infill is bounded by the innermost wall.
            // We take the last wall (innermost) and offset it inwards by half nozzle size
            // to reach the actual edge of the extrusion.
            Paths64 innermostWall = walls.get(walls.size() - 1);
            infillBoundary = Clipper.InflatePaths(innermostWall, -0.5 * nozzleSize * SCALE, JoinType.Miter, EndType.Polygon);
        }

        if (infillBoundary == null || infillBoundary.isEmpty() || spacing <= 0) {
            return new Paths64();
        }

        Rect64 bounds = Clipper.GetBounds(infillBoundary);
        long centerX = (bounds.left + bounds.right) / 2;
        long centerY = (bounds.top + bounds.bottom) / 2;

        long width = bounds.right - bounds.left;
        long height = bounds.bottom - bounds.top;
        // Use diagonal to ensure coverage even when rotated
        long diag = (long) Math.sqrt(width * width + height * height) + 1000; // Extra margin

        Paths64 allLines = new Paths64();
        switch (pattern) {
            case RECTILINEAR:
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle));
                break;
            case GRID:
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle));
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle + 90));
                break;
            case TRIANGLES:
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle));
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle + 60));
                allLines.addAll(generateParallelLines(centerX, centerY, diag, spacing, angle + 120));
                break;
        }

        // Perform clipping
        Clipper64 clipper = new Clipper64();
        clipper.addOpenSubject(allLines);
        clipper.addClip(infillBoundary);

        Paths64 clippedLines = new Paths64();
        Paths64 dummyClosed = new Paths64();
        clipper.Execute(ClipType.Intersection, FillRule.EvenOdd, dummyClosed, clippedLines);

        return clippedLines;
    }

    /**
     * Generates a set of parallel lines covering a square area.
     *
     * @param cX        Center X coordinate.
     * @param cY        Center Y coordinate.
     * @param range     The length of the area to cover (diagonal of the bounding box).
     * @param spacing   Distance between lines in model units.
     * @param angleDeg  Angle of the lines in degrees.
     * @return A {@link Paths64} containing the generated lines.
     */
    private Paths64 generateParallelLines(long cX, long cY, long range, float spacing, float angleDeg) {
        Paths64 lines = new Paths64();
        double angleRad = Math.toRadians(angleDeg);
        double cosA = Math.cos(angleRad);
        double sinA = Math.sin(angleRad);

        long scaledSpacing = Math.round(spacing * SCALE);
        if (scaledSpacing <= 0) {
            return lines;
        }

        long halfRange = range / 2;

        // We iterate across the diagonal to generate parallel lines.
        // d is the offset from the center line.
        for (long d = -halfRange; d <= halfRange; d += scaledSpacing) {
            // (px, py) is a point on the line at distance d from the center.
            // The direction of the lines is (cosA, sinA).
            // The direction of the offset is (-sinA, cosA).
            double px = cX + d * (-sinA);
            double py = cY + d * cosA;

            // Calculate endpoints of the line segment
            long x1 = Math.round(px - halfRange * cosA);
            long y1 = Math.round(py - halfRange * sinA);
            long x2 = Math.round(px + halfRange * cosA);
            long y2 = Math.round(py + halfRange * sinA);

            Path64 line = new Path64();
            line.add(new Point64(x1, y1));
            line.add(new Point64(x2, y2));
            lines.add(line);
        }

        return lines;
    }
}
