/*
 * aSlicer - 3D model processing tool.
 * Copyright (C) 2026 cz.ad.print3d.aslicer contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package cz.ad.print3d.aslicer.logic.core.filler;

import clipper2.core.Paths64;
import java.util.List;

/**
 * FillerGenerator defines the interface for all infill generation algorithms.
 * It takes boundary polygons and printing parameters and returns a set of paths.
 */
public interface FillerGenerator {
    /**
     * Generates infill paths for a given boundary.
     *
     * @param walls         The list of wall paths for the current layer, as generated by WallTracer.
     *                      Each element in the list represents a wall level (from outer to inner).
     * @param originalLayer The original boundary paths of the layer (used if no walls are present).
     * @param nozzleSize    The width of the extrusion line (nozzle diameter).
     *                      Used to calculate the infill boundary offset.
     * @param spacing       The distance between parallel infill lines (in model units, e.g., mm).
     * @param angle         The base angle for the infill pattern in degrees.
     * @param altitude      The vertical coordinate (typically Y in this slicer's context) of the current layer.
     * @return A {@link Paths64} containing the generated infill paths.
     */
    Paths64 generateInfill(List<Paths64> walls, Paths64 originalLayer, float nozzleSize, float spacing, float angle, float altitude);
}
