package cz.ad.print3d.aslicer.logic.model.format.mf3.prusa;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Represents the slicer settings found in Metadata/Slic3r_PE.config.
 * These settings are stored in an INI-like format where each line starts with a semicolon and a space.
 */
public class Mf3PrusaSettings {

    private final Map<String, String> settings;
    private static final Pattern LINE_PATTERN = Pattern.compile("^;\\s*([^=]+?)\\s*=\\s*(.*?)\\s*$");

    /**
     * Constructs an empty Prusa settings object.
     */
    public Mf3PrusaSettings() {
        this.settings = new LinkedHashMap<>();
    }

    /**
     * Constructs a Prusa settings object with the given settings map.
     *
     * @param settings the settings map
     */
    public Mf3PrusaSettings(final Map<String, String> settings) {
        this.settings = new LinkedHashMap<>(settings);
    }

    /**
     * Parses the settings from the content of a Slic3r_PE.config file.
     *
     * @param content the file content
     * @return a new Mf3PrusaSettings object
     */
    public static Mf3PrusaSettings parse(final String content) {
        Map<String, String> map = new LinkedHashMap<>();
        try (Scanner scanner = new Scanner(content)) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine().trim();
                Matcher matcher = LINE_PATTERN.matcher(line);
                if (matcher.matches()) {
                    map.put(matcher.group(1), matcher.group(2));
                }
            }
        }
        return new Mf3PrusaSettings(map);
    }

    /**
     * Returns all settings as a map.
     *
     * @return the settings map
     */
    public Map<String, String> getSettings() {
        return Collections.unmodifiableMap(settings);
    }

    /**
     * Returns a specific setting value.
     *
     * @param key the setting key
     * @return the value, or null if not found
     */
    public String get(final String key) {
        return settings.get(key);
    }

    /**
     * Returns the bed temperature setting.
     * 
     * @return bed temperature, or null if not set
     */
    public String getBedTemperature() {
        return get("bed_temperature");
    }

    /**
     * Returns the nozzle temperature for the first layer.
     * 
     * @return first layer temperature, or null if not set
     */
    public String getFirstLayerTemperature() {
        return get("first_layer_temperature");
    }

    /**
     * Returns the layer height setting.
     * 
     * @return layer height, or null if not set
     */
    public String getLayerHeight() {
        return get("layer_height");
    }

    /**
     * Returns the fill density (infill) setting.
     * 
     * @return fill density, or null if not set
     */
    public String getFillDensity() {
        return get("fill_density");
    }

    /**
     * Returns the nozzle diameter.
     * 
     * @return nozzle diameter, or null if not set
     */
    public String getNozzleDiameter() {
        return get("nozzle_diameter");
    }

    /**
     * Returns the filament diameter.
     * 
     * @return filament diameter, or null if not set
     */
    public String getFilamentDiameter() {
        return get("filament_diameter");
    }

    /**
     * Returns the extrusion multiplier.
     * 
     * @return extrusion multiplier, or null if not set
     */
    public String getExtrusionMultiplier() {
        return get("extrusion_multiplier");
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Mf3PrusaSettings that = (Mf3PrusaSettings) o;
        return java.util.Objects.equals(settings, that.settings);
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(settings);
    }

    @Override
    public String toString() {
        return "Mf3PrusaSettings{" +
                "settingsCount=" + settings.size() +
                '}';
    }

    /**
     * Serializes the settings back to the Prusa INI-like format.
     *
     * @return the formatted settings string
     */
    public String serialize() {
        StringBuilder sb = new StringBuilder();
        // PrusaSlicer usually adds a header
        sb.append("; generated by aSlicer\n");
        for (Map.Entry<String, String> entry : settings.entrySet()) {
            sb.append("; ").append(entry.getKey()).append(" = ").append(entry.getValue()).append("\n");
        }
        return sb.toString();
    }
}
